import Header from "@/components/header/Header";
import "./globals.scss";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { roboto, montserrat } from "@/fonts";
import AuthProvider from "@/components/auth-provider/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ params, children }) {
  const searchParams = await params;

  const { locale } = searchParams;

  return (
    <html lang="en" suppressHydrationWarning={true} data-lt-installed="true">
      <body className={`${roboto.variable} ${montserrat.variable}`}>
        <Header locale={locale} />
        <main>
          <AuthProvider>{children}</AuthProvider>
        </main>
      </body>
    </html>
  );
}
